CREATE TABLE [dbo].[TblProduct]
(
	[ProductId] INT NOT NULL IDENTITY(1, 1), 
    [ProductCode] NVARCHAR(20) NOT NULL, 
    [CategoryId] INT NOT NULL, 
    [ModelId] INT NULL, 
    [ProductName] NVARCHAR(200) NOT NULL, 
    [ProductNameBilling] NVARCHAR(200) NOT NULL, 
    [ProductNameTrade] NVARCHAR(200) NOT NULL, 
    [UnitId] INT NOT NULL, 
    [CostNet] DECIMAL(12, 2) NOT NULL, 
    [CostVat] DECIMAL(12, 2) NOT NULL, 
    [CostTot] DECIMAL(12, 2) NOT NULL, 
    [PriceNet] DECIMAL(12, 2) NOT NULL, 
    [PriceVat] DECIMAL(12, 2) NOT NULL, 
    [PriceTot] DECIMAL(12, 2) NOT NULL, 
	[QtyStock] INT NOT NULL,
    [FlagVat] BIT NOT NULL CONSTRAINT DF_TblProduct_FlagVat DEFAULT 1, 
    [FlagActive] BIT NOT NULL CONSTRAINT DF_TblProduct_FlagActive DEFAULT 1, 
    [CreatedBy] BIGINT NOT NULL, 
    [CreatedDate] DATETIME NOT NULL, 
    [UpdatedBy] BIGINT NOT NULL, 
    [UpdatedDate] DATETIME NOT NULL, 
    CONSTRAINT [PK_TblProduct] PRIMARY KEY ([ProductId]), 
    CONSTRAINT [UK_TblProduct_Code] UNIQUE ([ProductCode]), 
    CONSTRAINT [FK_TblProduct_Category] FOREIGN KEY ([CategoryId]) REFERENCES [TblProductCategory]([CategoryId]), 
    CONSTRAINT [FK_TblProduct_Model] FOREIGN KEY ([ModelId]) REFERENCES [TblProductModel]([ModelId]), 
    CONSTRAINT [FK_TblProduct_Unit] FOREIGN KEY ([UnitId]) REFERENCES [TblUnit]([UnitId])
)
