CREATE TABLE [dbo].[TblQuotation]
(
	[QuotationId] INT NOT NULL IDENTITY(1, 1), 
    [QuotationNo] NVARCHAR(20) NOT NULL , 
	[QuotationDate] DATETIME NOT NULL,
	[QuotationValidDay] INT NOT NULL CONSTRAINT DF_TblQuotation_ValidDay DEFAULT 30,
	[ConditionId] INT NULL,
	[OperationStartDate] Datetime NULL,
	[OperationEndDate] DateTime NULL,
    [DueDate] DATETIME NULL, 
    [DeliveryDate] DATETIME NULL,
	[QuotationCreditDay] INT NOT NULL CONSTRAINT DF_TblQuotation_CreditDay DEFAULT 0,
    [SaleId] INT NOT NULL, 
    [SaleName] NVARCHAR(500) NOT NULL, 
    [CustomerId] INT NULL, 
	[CustomerName] NVARCHAR(500) NULL,
    [ContractName] NVARCHAR(500) NULL,
    [ContractEmail] NVARCHAR(500) NULL,
    [ContractPhone] NVARCHAR(500) NULL,
	[BillingAddress] NVARCHAR(MAX) NULL,
	[ShippingAddress] NVARCHAR(MAX) NULL,
    [QuotationRemark] NVARCHAR(MAX) NULL, 
	[SubTotalNet] AS dbo.cplQuotationPriceNet(QuotationId),
	[SubTotalVat] AS dbo.cplQuotationPriceVat(QuotationId),
	[SubTotalTot] AS dbo.cplQuotationPriceTot(QuotationId),
	[DiscountNet] AS dbo.cplQuotationDiscountNet(QuotationId),
	[DiscountVat] AS dbo.cplQuotationDiscountVat(QuotationId),
	[DiscountTot] AS dbo.cplQuotationDiscountTot(QuotationId),
	[DiscountCash] DECIMAL(12, 2) NOT NULL,
	[SummaryNet] AS dbo.cplQuotationSummaryNet(QuotationId),
	[SummaryVat] AS dbo.cplQuotationSummaryVat(QuotationId),
	[SummaryTot] AS dbo.cplQuotationSummaryTot(QuotationId),
	[StatusId] INT NOT NULL,
    [CreatedBy] BIGINT NOT NULL, 
    [CreatedDate] DATETIME NOT NULL, 
    [UpdatedBy] BIGINT NOT NULL, 
    [UpdateDate] DATETIME NOT NULL, 
	[DeletedBy] INT NULL,
	[DeletedDate] DATETIME NULL,
	[DeletedReason] NVARCHAR(MAX) NULL,
    CONSTRAINT [PK_TblQuotation] PRIMARY KEY ([QuotationId]), 
    CONSTRAINT [FK_TblQuotation_Status] FOREIGN KEY ([StatusId]) REFERENCES [EnmStatusQuotation]([StatusId]), 
    CONSTRAINT [FK_TblQuotation_Sale] FOREIGN KEY ([SaleId]) REFERENCES [TblEmployee]([EmpId]), 
    CONSTRAINT [FK_TblQuotation_Customer] FOREIGN KEY ([CustomerId]) REFERENCES [TblCustomer]([CustomerId])



)
