CREATE TABLE [dbo].[TblSaleOrder]
(
	[SaleOrderId] INT NOT NULL IDENTITY(1, 1), 
    [SaleOrderNo] NVARCHAR(20) NOT NULL, 
    [SaleOrderDate] DATETIME NULL, 
	[OperationStartDate] Datetime NULL,
	[OperationEndDate] DateTime NULL,
    [QuotationNo] NVARCHAR(20) NULL, 
    [CustomerId] INT NULL, 
    [CustomerName] NVARCHAR(500) NULL, 
    [ContractName] NVARCHAR(500) NULL, 
    [ConditionId] INT NULL, 
    [PoNo] NVARCHAR(50) NULL, 
    [SaleId] INT NULL, 
    [SaleName] NVARCHAR(500) NULL, 
    [BillingAddress] NVARCHAR(MAX) NULL, 
    [ShippingAddress] NVARCHAR(MAX) NULL, 
    [SaleOrderRemark] NVARCHAR(MAX) NULL, 
    [StatusId] INT NOT NULL DEFAULT 1, 
    [CreatedBy] BIGINT NOT NULL, 
    [CreatedDate] DATETIME NOT NULL, 
    [UpdatedBy] BIGINT NOT NULL, 
    [UpdateDate] DATETIME NOT NULL, 
    [CancelReason] NVARCHAR(MAX) NULL, 
    [SubTotalNet] AS dbo.cplSaleOrderPrice(SaleOrderId,'PriceNet') , 
    [SubTotalVat] AS dbo.cplSaleOrderPrice(SaleOrderId,'PriceVat') ,
    [SubTotalTot] AS dbo.cplSaleOrderPrice(SaleOrderId,'PriceTot') ,
    [DiscountNet] AS dbo.cplSaleOrderPrice(SaleOrderId,'DiscountNet') ,
    [DiscountVat] AS dbo.cplSaleOrderPrice(SaleOrderId,'DiscountVat') ,
    [DiscountTot] AS dbo.cplSaleOrderPrice(SaleOrderId,'DiscountTot') ,
    [DiscountCash] DECIMAL(12, 2) NULL, 
    [SummaryNet] AS dbo.cplSaleOrderPrice(SaleOrderId,'SummaryNet') ,
    [SummaryVat] AS dbo.cplSaleOrderPrice(SaleOrderId,'SummaryVat') ,
    [SummaryTot] AS dbo.cplSaleOrderPrice(SaleOrderId,'SummaryTot'),
	[DeliveryDate] DATETIME NULL, 
    [SaleOrderCreditDay] INT NOT NULL DEFAULT 0, 
    CONSTRAINT [PK_TblSaleOrder] PRIMARY KEY ([SaleOrderId]), 
	CONSTRAINT [FK_TblSaleOrder_Sale] FOREIGN KEY ([SaleId]) REFERENCES [TblEmployee]([EmpId]), 		
    CONSTRAINT [FK_TblSaleOrder_Customer] FOREIGN KEY ([CustomerId]) REFERENCES [TblCustomer]([CustomerId])
)
